mozilla-services/shavar-prod-lists

- disconnect-blacklist.json
Supersedes https://github.com/mozilla-services/shavar-prod-lists/pull/14 with a rebased commit for merging.
> bug 1258037: Add dnt:eff to itisatracker.com

- scripts/json_verify.py
From our etherpad: https://public.etherpad-mozilla.org/p/shavarlist23
> assert itisatracker.com is in the block host uris

- disconnect-blacklist.json
- disconnect-entitylist.json
This supersedes https://github.com/mozilla-services/shavar-prod-lists/pull/30 with an extra commit to add api-maps.yandex.ru as a Yandex resource domain.
> Disconnect update 2017 12 05

- disconnect-entitylist.json
https://bugzilla.mozilla.org/show_bug.cgi?id=1449372
> Bug 1449372 - Add mailchi.mp as a MailChimp domain.

- README.md
This addresses the documentation issue identified in Issue #37.
> Update documentation to reflect new source of Disconnect domain remapping

- disconnect-blacklist.json
- disconnect-entitylist.json
Hey, figured I would push this since a lot of the changes are pretty overdue and we're not there yet on the categories - hopefully the next update (November/December?) will primarily be centered around adding cryptominers and fleshing out the category tags.
> Pull in latest disconnect blacklist, update entitylist to match

- disconnect-entitylist.json
PR to address breakage when using sharepoint (owned by Microsoft) filed here: https://github.com/disconnectme/disconnect-tracking-protection/issues/69
> adds sharepoint to microsoft entity list

- disconnect-blacklist.json
- disconnect-entitylist.json
Cryptominers are now moved to a new category `Cryptomining` and are no longer designated with 'cryptominer' tag
> adds new ‘Cryptomining’ top-level category, latest tracker modifications

- disconnect-blacklist.json
- disconnect-entitylist.json
This is similar to the last PR. Fingerprinters are no longer identified using tags and are broken out in their own top-level category: `Fingerprinting`
> adds new top-level category, Fingerprinting. removes previous tags

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR addresses issues with #56 (duplicate domains, augur back as tracker), some new trackers, and updates several corp/domain associations
> Fixes duplicate domains, adds new trackers, updates corp/domain association

- disconnect-blacklist.json
- disconnect-entitylist.json
https://github.com/disconnectme/disconnect-tracking-protection/commit/8858b97171c6e32028312a0598ad39c9a9d8a7b3
https://github.com/disconnectme/disconnect-tracking-protection/commit/9666265d0a26fbcc65a20c1021517a44a5ade580
https://github.com/disconnectme/disconnect-tracking-protection/commit/156e9c67582134e1511209c1cc7dea5710eab4a5
> adds recent disconnect list changes

- social-tracking-protection-blacklist.json
Adds 5 new lists for social tracking protection.
Note: to test creating these lists, you'll also need to be on [this branch of shavar-list-creation](https://github.com/mozilla-services/shavar-list-creation/pull/83) and add  these corresponding config sections to `shavar_list-creation.ini` (also available in the sample file in the branch):
```
[social-tracking-protection]
disconnect_url=https://raw.githubusercontent.com/mozilla-services/shavar-prod-lists/add-socialtracker-tag-1559217/social-tracking-protection-blacklist.json
categories=Facebook,Twitter,LinkedIn,YouTube
output=social-tracking-protection-digest256
s3_key=tracking/social-tracking-protection-digest256
[social-tracking-protection-facebook]
disconnect_url=https://raw.githubusercontent.com/mozilla-services/shavar-prod-lists/add-so …
```
> bug 1559217: add social-tracker tags

- disconnect-blacklist.json
- disconnect-entitylist.json
Adds the following commits only:
https://github.com/disconnectme/disconnect-tracking-protection/commit/f39cf6021449f3ce1940301aa48ee3c37514de14
https://github.com/disconnectme/disconnect-tracking-protection/commit/c03538dcc03b909c78be1ed660ea938bc6d74c66
> removes adobe tag manager and pepperjam.com

- disconnect-blacklist.json
- disconnect-entitylist.json
In order to roll out changes for https://github.com/mozilla-services/shavar-list-creation/issues/90 in Shavar we need to make sure all the versioned lists are up to date with Master branch since all versions of Firefox was using the master branch before we introduced the version lists.
> Get 69 Versioned List to Latest on Master

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR contains only removals and no added trackers. Please see individual commits for more details.
> Recent Disconnect tracker removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70 - Recent Disconnect tracker removals

- disconnect-blacklist.json
- disconnect-entitylist.json
See individual commits for full details
> Recent Disconnect list additions

- README.md
> Simplify list descriptions and add release process

- disconnect-blacklist.json
> 72 - Recent Disconnect tracker removals 2020 01 removals 0

- disconnect-blacklist.json
> 71 - Recent Disconnect tracker removals 2020 01 removals 0

- disconnect-blacklist.json
> 73 - Recent Disconnect tracker removals 2020 01 removals 0

- disconnect-blacklist.json
> 70 - Recent Disconnect tracker removals 2020 01 removals 0

- disconnect-blacklist.json
> 69 - Recent Disconnect tracker removals 2020 01 removals 0

- disconnect-blacklist.json
See: https://github.com/mozilla-services/shavar-prod-lists/issues/69
> removes `Disconnect` category and remaps to appropriate categories

- disconnect-blacklist.json
- disconnect-entitylist.json
Removes Viral-loops.com see: https://github.com/disconnectme/disconnect-tracking-protection/commit/9392141916ca8b06567cd95d72e8eb2d8cf1d7e3
Adds specific subdomains for Friends2Follow: https://github.com/disconnectme/disconnect-tracking-protection/commit/5f52643e948de88c786364d3bb87cd7d29ecdc5b
Adds multicloud-ibm.com to IBM entity: https://github.com/disconnectme/disconnect-tracking-protection/commit/f0bc1b022e4c2f3f51691a0e7af03b1f44eac41e
> Recent disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 - 2020 02 removals 0 and Remove Disconnect Category

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2020 02 removals 0 and Remove Disconnect Categor

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2020 02 removals 0 and Remove Disconnect Categor

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2020 02 removals 0 and Remove Disconnect Categor

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2020 02 removals 0 and Remove Disconnect Categor

- disconnect-blacklist.json
> 73.0 2020 02 removals 2

- disconnect-blacklist.json
> 72.0 2020 02 removals 2

- disconnect-blacklist.json
> 71.0 2020 02 removals 2

- disconnect-blacklist.json
> 69.0 2020 02 removals 2

- disconnect-blacklist.json
> 70.0 2020 02 removals 2

- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/fb86ad503785a7491b47ac8eaf04d3bf6b11c9f2
> Adds internalfb.com to Facebook properties (entity list update)

- disconnect-blacklist.json
- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/e751049be42ad4fe4e269c941d9bd9ffbaa3a315
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/e048cc27d0b3ba093fc352279991e4286e7a2441
> Adds recent Disconnect list additions

- disconnect-entitylist.json
> 73.0 2020 02 removals 3

- disconnect-entitylist.json
> 69.0 2020 02 removals 3

- disconnect-entitylist.json
Related to PR #128 
#
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/fb86ad503785a7491b47ac8eaf04d3bf6b11c9f2
> 71.0 2020 02 removals 3

- disconnect-entitylist.json
Related to PR #128
#
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/fb86ad503785a7491b47ac8eaf04d3bf6b11c9f2
> 70.0 2020 02 removals 3

- disconnect-entitylist.json
Related to PR #128
#
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/fb86ad503785a7491b47ac8eaf04d3bf6b11c9f2
> 72.0 2020 02 removals 3

- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/ff44678da916005a876ef0dafcc239ee122bc88d
> adds nest.com to Google properties

- disconnect-blacklist.json
- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/0779bf2f14c56eb07d4a5e05ec3689e6f6e7f3c7
> Recent removals from Disconnect

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2020 03 removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2020 03 removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2020 03 removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2020 03 removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2020 03 removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2020 03 removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2020 03 removals 0

- README.md
> Add language to the readme that describes interventions

- scripts/json_verify.py
This PR will resolve #120 and follows my previous PR #143
> add more checks in travic ci

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2020 03 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2020 03 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2020 03 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2020 03 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2020 03 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2020 03 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2020 03 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2020 04 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2020 04 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2020 04 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2020 04 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2020 04 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2020 04 removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
> 76.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 04 removals 2

- disconnect-blacklist.json
- disconnect-entitylist.json
adds home.neustar property to Neustar entity: https://github.com/disconnectme/disconnect-tracking-protection/commit/4636f8bda382a880828601f0509362f3999b7216
> Recent Disconnect removals or entity updates (April#02)

- disconnect-blacklist.json
- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/6410e1d5fe1cca3ac317f21ce6fccc139d641bb4
> Recent Disconnect entity updates or removals (2020-06-0)

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2020 06 entity updates or removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2020 06 entity updates or removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2020 06 entity updates or removals 0

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2020 06 entity updates or removals 0

- LICENSE
- README.md
> 69.0 license update

- LICENSE
> 74.0 add more details on license

- LICENSE
> 78.0 add more details on license

- LICENSE
> 69.0 add more details on license

- LICENSE
> 73.0 add more details on license

- LICENSE
> 75.0 add more details on license

- LICENSE
> 72.0 add more details on license

- LICENSE
> 71.0 add more details on license

- LICENSE
> 77.0 add more details on license

- LICENSE
> 76.0 add more details on license

- LICENSE
> 70.0 add more details on license

- disconnect-entitylist.json
- scripts/json_verify.py
> 78.0 updates entitylist to include key for license

- disconnect-entitylist.json
- scripts/json_verify.py
> 76.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 69.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 72.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 70.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 73.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 77.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 71.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 74.0 updates license for entitylist

- disconnect-entitylist.json
- scripts/json_verify.py
> 75.0 updates license for entitylist

- disconnect-blacklist.json
- disconnect-entitylist.json
> Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
See:
Merge conflict resolved by removing Poool resources and properties from entitylist
> 75.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
See:
Merge conflict resolved by removing Poool resources and properties from entitylist
> 76.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
See:
Merge conflict resolved by removing Poool resources and properties from entitylist
> 77.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 78.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 Disconnect entity updates/removals

- disconnect-blacklist.json
- disconnect-entitylist.json
See:
https://github.com/disconnectme/disconnect-tracking-protection/commit/a0ec3344fcee75094f986921426a3fb5dc95bc52
https://github.com/disconnectme/disconnect-tracking-protection/commit/8d6d3535aea733a5b9851254bd62a10f6684e6ed
https://github.com/disconnectme/disconnect-tracking-protection/commit/b142f4aef0292143f869e38f77d6cf5818564842
https://github.com/disconnectme/disconnect-tracking-protection/commit/92f23afe4f675a9cb25687d391ce2ced64eecab1
> Recent Disconnect additions

- disconnect-entitylist.json
> Recent Disconnect entity updates or removals (7-1) 

- disconnect-entitylist.json
> 69.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 70.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 71.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 72.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 73.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 74.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 75.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 76.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 77.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 78.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 79.0 adds e.gg as Facebook property

- disconnect-entitylist.json
> 80.0 adds e.gg as Facebook property

- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/65f3f14945dd43c92952569fee1185d301e2a20e
https://github.com/disconnectme/disconnect-tracking-protection/commit/f8d693f720804896cece18a3f0a83ee969f15879
> Recent Disconnect list entity updates or removals (2020-08-1)

- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/65f3f14945dd43c92952569fee1185d301e2a20e
https://github.com/disconnectme/disconnect-tracking-protection/commit/f8d693f720804896cece18a3f0a83ee969f15879
Related to #308
> Adds more properties to the eBay entity

- disconnect-blacklist.json
- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/dc997df6c61f4a0165e18469428349dd59299ba2
https://github.com/disconnectme/disconnect-tracking-protection/commit/4976a93613ccdb43ff0d33fa4fb3e6e6757a73fd
https://github.com/disconnectme/disconnect-tracking-protection/commit/eea6910d396923dd9dceb1ce9de2241a3055a6e4
> Recent (2020-08#1) Disconnect list additions 

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 69.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 70.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 71.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 72.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 73.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 74.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 75.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 76.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 77.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 78.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 79.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- social-tracking-protection-blacklist.json
> 80.0 Merge Disconnect change of Crashlytics

- disconnect-blacklist.json
- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/eea6910d396923dd9dceb1ce9de2241a3055a6e4
> Changes the fingerprinting category to two sub-categories

- disconnect-blacklist.json
> 80.0 Rename fingeprinting category

- disconnect-blacklist.json
> 79.0 Rename fingeprinting category

- disconnect-blacklist.json
> 78.0 Rename fingeprinting category

- disconnect-blacklist.json
> 77.0 Rename fingeprinting category

- disconnect-blacklist.json
> 76.0 Rename fingeprinting category

- disconnect-blacklist.json
> 75.0 Rename fingeprinting category

- disconnect-blacklist.json
> 74.0 Rename fingeprinting category

- disconnect-blacklist.json
> 73.0 Rename fingeprinting category

- disconnect-blacklist.json
> 72.0 Rename fingeprinting category

- disconnect-blacklist.json
> 71.0 Rename fingeprinting category

- disconnect-blacklist.json
> 70.0 Rename fingeprinting category

- disconnect-blacklist.json
> 69.0 Rename fingeprinting category

- README.md
Update reference to Fingerprinting category to FingerprintingInvasive.
> Update README with new Fingerprinting category name

- disconnect-blacklist.json
- scripts/compare_disconnect.py
I checked diffs between Disconnect and Shavar, and found this missing entry.
See also: #324
> Check Disconnect.me diff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 80.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 78.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 77.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 76.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 72.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 73.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 74.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 71.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 70.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 69.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 75.0 09 01 disconnect resolve dff

- disconnect-blacklist.json
- scripts/compare_disconnect.py
> 79.0 09 01 disconnect resolve dff

- disconnect-entitylist.json
Revert after changed checksum forces an update to the S3
> Check changing order changes checksum

- disconnect-blacklist.json
- disconnect-entitylist.json
> 82.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 81.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 80.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 79.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 78.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 77.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 76.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2020 10 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
See:
https://github.com/disconnectme/disconnect-tracking-protection/commit/96b742d5bdd61dc9813bee005911984a30f534e5
https://github.com/disconnectme/disconnect-tracking-protection/commit/888fadbd36abf6c623314fc1a3d026bd1c604467
https://github.com/disconnectme/disconnect-tracking-protection/commit/295372a8679b6cff489a997a9d8f6b1814fa1eb3
> Recent (2020-10#1) Disconnect list additions

- disconnect-entitylist.json
> 69.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 71.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 73.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 75.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 77.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 79.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 83.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 70.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 72.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 74.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 76.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 78.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 80.0 2020 11 entity updates or removals 1

- disconnect-entitylist.json
> 82.0 2020 11 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> Recent (2020-12#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 82.0 2020 12 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 80.0 2020 12 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 78.0 2020 12 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 76.0 2020 12 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2020 12 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2020 12 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2020 12 entity updates or removals 1

- README.md
> Add timeline for temporary exceptions with partner

- disconnect-blacklist.json
- disconnect-entitylist.json
These changes are primarily updating the corp ownership of currently added entities and adding new properties/resources of current entities.
> Recent (2021-01#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 77.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 79.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 81.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 83.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 85.0 2021 01 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
Please see:
https://github.com/disconnectme/disconnect-tracking-protection/commit/9ab9425699f55cd42d57b67473b990213dca59a7
https://github.com/disconnectme/disconnect-tracking-protection/commit/25d7c77463e1f900ada81ce39de8266c68fe38e7
> Recent (2021-01#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
Please see: https://github.com/disconnectme/disconnect-tracking-protection/commit/e01b37ac4a9d952d8129deed829f338454acaac6
> Recent (2021-03#1) Disconnect entity updates or removals 

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 77.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 79.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 81.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 83.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 85.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 87.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 76.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 78.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 80.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 82.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 84.0 2021 03 entity updates or removals 1

- README.md
- disconnect-blacklist.json
- disconnect-entitylist.json
> 86.0 2021 03 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list entity updates, removals, or domains going from invasive to general fingerprinting.
> Recent (2021-04#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 89.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 87.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 85.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 83.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 81.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 79.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 77.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 88.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 86.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 84.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 82.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 80.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 78.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 76.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2021 04 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list entity updates and removals. Please see individual commits for details. @say-yawn, please let me know if you have any questions. Thanks!
> Recent (2021-06#1) Disconnect entity updates or removals

- disconnect-entitylist.json
> 70.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 72.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 74.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 76.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 80.0 2021 06 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 90.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 71.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 73.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 75.0 2021 06 entity updates or removals 1

- disconnect-entitylist.json
> 77.0 2021 06 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list entity updates, removals, or updating fingerprinting categorization from invasive to general. Please see individual commits for details. @say-yawn, please let me know if you have any questions. This should resolve https://github.com/mozilla-services/shavar-prod-lists/issues/525. Thanks!
> Recent (2021-07#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 89.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 87.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 85.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 83.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 81.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 79.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 77.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 90.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 88.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 86.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 84.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 82.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 80.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 78.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 76.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2021 07 entity updates or removals 1

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR contains recent Disconnect list additions. Please see individual commits for details. @say-yawn, please let me know if you have any questions. Thanks!
> Recent (2021-07#1) Disconnect List additions 

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list entity updates, removals, or updating fingerprinting categorization from invasive to general. Please see individual commits for details. @say-yawn, please let me know if you have any questions. Thanks!
> Recent (2021-11#3) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> 95.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 91.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 89.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 87.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 85.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 83.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 81.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 79.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 77.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 75.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 73.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 71.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 69.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 94.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 92.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 90.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 88.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 70.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 84.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 78.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 74.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 76.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 86.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 72.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 80.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
> 82.0 2021 11 entity updates or removals 3

- disconnect-blacklist.json
- disconnect-entitylist.json
Please See: https://github.com/disconnectme/disconnect-tracking-protection/commit/3cc4fca2946654d6a0987f3a1316d80069cce521
https://github.com/disconnectme/disconnect-tracking-protection/commit/e8e755f151af42e7a8884c52f4db4879579f5b30
https://github.com/disconnectme/disconnect-tracking-protection/commit/44fceba8494af171ef0f7fefa002d27e2de5a78a
Please let us know if you have any questions, @say-yawn and team. Thanks!
> Adds Email and EmailStrict categories (2022-02-24)

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR contains recent Disconnect list additions.
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/4f6f8f2d6f58bf8b3b6bf9385438af80b4b52223
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/056d0f19c211b5a6f7a456a36238a12b7198be3b
say-yawn - These changes are primarily new Email and EmailStrict additions and one advertising tracker addition. Please let me know if you have any questions. Thanks!
> Recent (2022-04#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR contains recent Disconnect list additions.
@say-yawn  - please let me know if you have any questions. Thanks!
> Recent (2022-08#1) Disconnect List additions

- disconnect-entitylist.json
Recent Disconnect list entity updates or removals. Please see individual commits for details. @say-yawn, please let me know if you have any questions. Thanks!
> Recent (2022-08#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR contains recent Disconnect list additions.
@say-yawn - please let me know if you have any questions. Thanks!
> Recent (2022-10#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
Please see individual commits: 
https://github.com/disconnectme/disconnect-tracking-protection/commit/73f0ba8d489b40c3021029288ad6e02ad7435a4c
> Recent (2022-12#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR contains recent Disconnect list additions.
@say-yawn - please let me know if you have any questions. Thanks!
> Recent (2022-12#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
This PR contains recent Disconnect list additions. Please see individual commits for details. Let me know if you have any questions. Thanks.
> Recent (2023-06#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list additions. Please see individual commits for details. Please let me know if you have any questions. Thanks!
> Recent (2023-09#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list additions and category re-reviews. Please see individual commits for details. Please let me know if you have any questions. Thanks!
> (2023-12#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list additions, category re-reviews, and other recent changes. Please see individual commits for details. Please let me know if you have any questions. Thanks!
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/c56b2b8c5f624f6863bc6a6d4dfa7ff1810396ed
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/d002642db8e0b09b703e10b8b49f32e119683866
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/65fd769e78db5fcf06277f1a76af03319980ec5d
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/f68519a36a4b01e70cbcd2938a3b2a098cc7d3b7
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/5050916720194ed71df508ba1118816c7fcd06e9
See: …
> (2024-04#2) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list entity updates and removals. Please see individual commits for details. Please let me know if you have any questions. Thanks @Trikolon!
> Recent (2024-05#1) Disconnect entity updates or removals

- .github/workflows/CODEOWNERS
This allows us to automatically request review on new PRs from anti-tracking group members.
> Add reviewer group for list changes.

- disconnect-blacklist.json
- disconnect-entitylist.json
> Recent (2024-06#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list additions and other recent changes. Please see individual commits for details. Please let me know if you have any questions. Thanks!
> (2024-10#1) Disconnect List additions

- disconnect-blacklist.json
- disconnect-entitylist.json
> Recent (2024-10#1) Disconnect entity updates or removals

- disconnect-blacklist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/cfd2b663e4623917b8cf5228b54d13ea1bb7fbe2
> Recent (2024-11#1) Disconnect entity updates or removals

- disconnect-entitylist.json
See: https://github.com/disconnectme/disconnect-tracking-protection/commit/060435617b7b893b7478238027606e1366b6e321
> Recent (2024-11#2) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> Recent (2024-12#1) Disconnect entity updates or removals

- disconnect-entitylist.json
> Recent (2025-01#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
> Recent (2025-03#1) Disconnect entity updates or removals

- disconnect-blacklist.json
Removes CMPs from other categories.
> Updates `ConsentManagers`

- disconnect-entitylist.json
Recent Disconnect list entity updates, re-categorizations, and removals. Please see individual commits for details. Please let me know if you have any questions. Thanks!
> Recent (2025-04#2) Disconnect entity updates, re-categorizations, and removals
