mozilla-services/shavar-prod-lists

- .travis.yml
- scripts/test.sh
This enables continuous integration testing of the JSON files in the repo.
If a PR includes valid JSON, it will look like this:
- https://github.com/fmarier/shavar-prod-lists/pull/1
- https://travis-ci.org/fmarier/shavar-prod-lists/builds/85664352
On the other hand, if it contains invalid JSON, it will look like this:
- https://github.com/fmarier/shavar-prod-lists/pull/2
- https://travis-ci.org/fmarier/shavar-prod-lists/builds/85664426
> Setup Travis

- disconnect-blacklist.json
- disconnect-entitylist.json
Blocking all of Yandex is probably too broad and may cause a bad UX on some sites.
> More specific Yandex service blocking

- disconnect-entitylist.json
@mdeschamps does that look good to you?
I only added `digits.com` to the `properties` section. Will other properties be loading subresources from this domain? (e.g. `twitter.com` loading `digits.com/foo.js`)
> Add digits.com and fabric.io to the Twitter org

- scripts/json_verify.py
This shows more detailed error messages when the script finds a non-ascii character in the json. E.g.,
```
old_disconnect-blacklist.json : invalid
Error: Bad URI: facébook.com   	: in line 8
Error: Bad URI: ytså.net       	: in line 47
```
> fix bug 1289621: catch non-ascii character hosts

- disconnect-entitylist.json
- scripts/json_verify.py
Implemented the logic and found existing duplicates:
```
disconnect-entitylist.json : invalid
Dupe: Dupe host: tumblr.com    	 in line 9363
Dupe: Dupe host: buzzcity.com  	 in line 2014
Dupe: Dupe host: adonnetwork.com       	 in line 925
Dupe: Dupe host: i-behavior.com	 in line 3716
Dupe: Dupe host: flurry.com    	 in line 3280
Dupe: Dupe host: tumblr.com    	 in line 9366
Dupe: Dupe host: buzzcity.com  	 in line 2017
Dupe: Dupe host: adonnetwork.com       	 in line 929
Dupe: Dupe host: i-behavior.com	 in line 3720
```
What should we do with the existing duplicates?
> for #16: check duplicate entities in json_verify

- disconnect-blacklist.json
- disconnect-entitylist.json
Builds on https://github.com/mozilla-services/shavar-prod-lists/pull/23 ...
> Disconnect list update

- disconnect-entitylist.json
For https://bugzilla.mozilla.org/show_bug.cgi?id=1415305 ... so far we only know about yadi.sk web property for Yandex, but there may be more to add later.
@fmarier - look good?
> fix bug #1415305 - add yadi.sk Yandex property

- scripts/json_verify.py
In https://github.com/mozilla-services/shavar-list-creation-config/pull/35 and https://github.com/mozilla-services/shavar-list-creation/pull/62 we added support for Disconnect's new sub-category tags. This PR updates the list verification script to accept a list with these tags and include a summary in the output.
> Add category support to list verification script

- README.md
Update to the new link to the Disconnect mapping file and clarified how the mapping file is used in list creation. Removed the "this remapping is temporary" message, since that has been there for the last 4 years (since 5b24f7759b5d0fa16db15c0309db7c7a6374f263).
> Clarify Disconnect category in README

- social-tracking-protection-blacklist.json
Adjusts the social tracking protection blocklist to match Disconnect's domains for each entity.
> fix mozilla-services/shavar-list-creation-config#52

- disconnect-blacklist.json
- disconnect-entitylist.json
- social-tracking-protection-blacklist.json
Supersedes https://github.com/mozilla-services/shavar-prod-lists/pull/71 with a commit to make STP block-list match new Disconnect domains.
Merging this will effectively bundle all the list updates together.
> Facebook and shareaholic updates from Disconnect for both blacklist and STP

- disconnect-blacklist.json
- disconnect-entitylist.json
adds blogspot.com as Google property: https://github.com/disconnectme/disconnect-tracking-protection/commit/e363db5b78752e7a2861bf5d9a931ef539f018f6
> Recent Disconnect list removals or entity updates

- README.md
This pull requests adds a TravisCI master build status badge to the project's README file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/mozilla-services/shavar-prod-lists/177)
> TravisCI status on the README

- disconnect-blacklist.json
- disconnect-entitylist.json
Related to PR #172
Adding the `google.com` to the `Content` category as per https://github.com/mozilla-services/shavar-prod-lists/issues/96#issuecomment-616792495
> 76.0 2020 04 removals 1

- scripts/json_verify.py
Remove references to "fingerprinting" and "cryptominer" tags from `json_verify.py`, as these tags are not used anymore. Update the docstring of `find_uris` to reflect the current structure of the tracker blocklist. This PR addresses https://github.com/mozilla-services/shavar-list-creation/issues/149
> Remove references to deprecated tags

- disconnect-blacklist.json
- disconnect-entitylist.json
Adds ad-score as invasive fingerprinter: https://github.com/disconnectme/disconnect-tracking-protection/commit/d1f6a992dcc6c02430aa13986d8b51d3de2a29df
adds ie8eamus.com as tracker and FingerprintingInvasive: https://github.com/disconnectme/disconnect-tracking-protection/commit/36ce842065f1a2d07a7c838c3776d31099073d17
Moves BounceExchange to FingerprintingInvasive: https://github.com/disconnectme/disconnect-tracking-protection/commit/a73a200122a5645b4a55191d886bce4446ee7150
> Recent (2020-09#1) Disconnect list additions

- disconnect-entitylist.json
See: Add oversightboard.com as Facebook property - https://github.com/disconnectme/disconnect-tracking-protection/commit/c1bdd21c5923456ca0d2312caa17b68ddff989e8
> Recent (2020-11#1) Disconnect list entity updates or removals

- .github/workflows/test.yml
- .travis.yml
- scripts/compare_disconnect.py
- scripts/compare_remote.py
- scripts/json_verify.py
Maintenance work to ensure that Shavar lists are not too different from Disconnect's lists.
#
Fix #403
> Compare shavar and disconnect

- README.md
We've decided to move the intervention policy into the wiki as we intend to use it more broadly than just for our list-based features.
> Migrate intervention policy to wiki page

- disconnect-blacklist.json
- disconnect-entitylist.json
Recent Disconnect list entity updates, removals, or updating fingerprinting categorization from invasive to general. Please see individual commits for details. @say-yawn, please let me know if you have any questions. Thanks!
Moves Refersion from invasive to general fp. See: https://github.com/disconnectme/disconnect-tracking-protection/commit/dab5b07e1a8b961cb2475cc7d66fc505bccbbc3b
Replaces vpsvc.com with vpdcp.com and vptms.com. See: https://github.com/disconnectme/disconnect-tracking-protection/commit/5b28d0adbafda7b6954251a4ff04b9707a260bf1
> Recent (2022-02#1) Disconnect entity updates or removals

- disconnect-blacklist.json
- disconnect-entitylist.json
- https://github.com/disconnectme/disconnect-tracking-protection/commit/d3e46468172e2ca81a51be911d9677fa53377588
- https://github.com/disconnectme/disconnect-tracking-protection/commit/baca82757acf7ec84de75ff3283c9ad52c3fc1b7
> Recent (2024-08#1) Disconnect entity updates or removals, adds`ConsentManagers` category

- disconnect-entitylist.json
Adds `ttvnw.net` as `Amazon` resource
> Recent (2025-06#1) Disconnect entity updates, re-categorizations, and removals 
